Ecommerce.Web/Entities/Gender.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ecommerce.Entities
{
    public class Gender
    {
        public int ID { get; set; }
        public string GenderName { get; set; }
        public bool Status { get; set; }

    }
}

Ecommerce.Web/Controllers/Gender/GenderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Ecommerce.Entities;
using Ecommerce.Web.Data;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce.Web.Controllers.Gender
{
    public class GenderController : Controller
    {
        private readonly ApplicationDbContext db;
        public GenderController(ApplicationDbContext _db)
        {

        }
        
        // GET: Gender
        public ActionResult Index()
        {
            var genderList = db.Genders.ToList();
            return View(genderList);
        }

        public ActionResult AddGender()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddGender(Ecommerce.Entities.Gender gender)
        {
            if (ModelState.IsValid)
            {
                db.Genders.Add(gender);
                db.SaveChanges();
            }
            return View(gender);
        }
    }
}

Ecommerce.Web/Views/Gender/AddGender.cshtml
@model Ecommerce.Entities.Gender
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content">
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2>Form Validation</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html"><i class="zmdi zmdi-home"></i> Aero</a></li>
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Forms</a></li>
                        <li class="breadcrumb-item active">Form Validation</li>
                    </ul>
                    <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <button class="btn btn-primary btn-icon float-right right_icon_toggle_btn" type="button"><i class="zmdi zmdi-arrow-right"></i></button>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <!-- Basic Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="body">
                            <form id="AddGenderForm" method="POST" action="@Url.Action("AddGender","Gender")">
                                <div class="form-group form-float">
                                    <input type="text" class="form-control" placeholder="Gender Name" name="GenderName" required>
                                </div>

                                <div class="form-group">
                                    <div class="checkbox">
                                        <input id="checkbox" type="checkbox">
                                        <label for="checkbox">I have read and accept the terms</label>
                                    </div>
                                </div>
                                <button id="GenderAddBtn" class="btn btn-raised btn-primary waves-effect" type="button">SUBMIT</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div id="imageTemplate" style="display:none">
    <img class='image img-thumbnail' src='' style="height:100px; width:100px" />
</div>
<script>
    $('#GenderAddBtn').click(function () {
        debugger;
         $.ajax({
         url: "@Url.Action("AddGender","Gender")",
         type: "post",
             data: $("#AddGenderForm").serialize()
     }).done(function (responses) {
         debugger;
         alert("Gender Save Succesfully");
         window.location.href = "@Url.Action("Index", "Gender")";
     }).fail(function () {

     });
    });
</script>

Ecommerce.Web/Views/Gender/Index.cshtml
@model IEnumerable<Ecommerce.Entities.Gender>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content">
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <h2></h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action("Dashboard","Dashboard")"><i class="zmdi zmdi-home"></i>Category  </a></li>
                        <li class="breadcrumb-item">Category</li>
                        <li class="breadcrumb-item active">List of Product Brand</li>
                    </ul>
                    <button class="btn btn-primary btn-icon mobile_menu" type="button"><i class="zmdi zmdi-sort-amount-desc"></i></button>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-12">
                    <button class="btn btn-primary btn-icon float-right right_icon_toggle_btn" type="button"><i class="zmdi zmdi-arrow-right"></i></button>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <a href="@Url.Action("AddGender","Gender")" class=" btn btn-info">Add Gender</a>
            <div class="row clearfix">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="table-responsive">
                            <table class="table table-hover product_item_list c_table theme-color mb-0">
                                <thead>
                                    <tr>
                                        
                                        <th>Product Name</th>
                                        <th data-breakpoints="sm xs md">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            
                                            <td><h5>@item.GenderName</h5></td>
                                            <td>
                                                <a href="@Url.Action("EditGender","Gender",new { ID=item.ID})" class="btn btn-default waves-effect waves-float btn-sm waves-green"><i class="zmdi zmdi-edit"></i></a>
                                                <a href="@Url.Action("DeleteGender","Gender",new { ID=item.ID});" class="btn btn-default waves-effect waves-float btn-sm waves-red"><i class="zmdi zmdi-delete"></i></a>
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="card">
                        <div class="body">
                            <ul class="pagination pagination-primary m-b-0">
                                <li class="page-item"><a class="page-link" href="javascript:void(0);"><i class="zmdi zmdi-arrow-left"></i></a></li>
                                <li class="page-item active"><a class="page-link" href="javascript:void(0);">1</a></li>
                                <li class="page-item"><a class="page-link" href="javascript:void(0);">2</a></li>
                                <li class="page-item"><a class="page-link" href="javascript:void(0);">3</a></li>
                                <li class="page-item"><a class="page-link" href="javascript:void(0);">4</a></li>
                                <li class="page-item"><a class="page-link" href="javascript:void(0);"><i class="zmdi zmdi-arrow-right"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>