Ecommerce.Web/Entities/Banner.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Ecommerce.Entities
{
   public class Banner
    {
        public int ID { get; set; }
        public string BannerName { get; set; }
        public bool Status { get; set; }
        public string ProductURL { get; set; }

        public virtual List<BannerPicture> BannerPictures { get; set; }
    }
}

Ecommerce.Web/Models/Banner/BannerModels.cs
using Ecommerce.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ecommerce.Web.Models
{
    public class CreateBannerModel
    {
        public int ID { get; set; }
        public string BannerName { get; set; }
        public bool Status { get; set; }
        public string ProductURL { get; set; }
        public string BannerPictures { get; set; }
        public virtual List<BannerPicture> BannerPictureList { get; set; }
    }
}

Ecommerce.Web/ViewModels/BannerViewModel.cs
using Ecommerce.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Ecommerce.Web.ViewModels
{
    public class BannerViewModel
    {
        public int ID { get; set; }
        public string SBannerName { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public virtual List<SecoundBannerPicture> SecoundBannerPictures { get; set; }
    }
}

Ecommerce.Web/Controllers/Banner/BannerController.cs
using Ecommerce.Entities;
using Ecommerce.Services.BannerServices;
using Ecommerce.Web.IServices;
using Ecommerce.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace Ecommerce.Web.Controllers
{
    public class BannerController : Controller
    {
        private readonly IBannerServices bannerServices;
        public BannerController(IBannerServices _bannerServices)
        {
            bannerServices = _bannerServices;
        }
        // GET: Banner
        public ActionResult Index()
        {
            var bannerlist = bannerServices.GetAllBanner();
            return View(bannerlist);
        }
        public ActionResult AddBanner()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddBanner(CreateBannerModel model)
        {
            Banner banner = new Banner();

            banner.BannerName = model.BannerName;
            banner.ProductURL = model.ProductURL;
            banner.Status = model.Status;


            if (!string.IsNullOrEmpty(model.BannerPictures))
            {
                var pictureIDs = model.BannerPictures
                    .Split(new char[] { ',' },
                    StringSplitOptions.RemoveEmptyEntries)
                    .Select(ID => int.Parse(ID)).ToList();

                banner.BannerPictures = new List<BannerPicture>();
                banner.BannerPictures.AddRange(pictureIDs
                    .Select(x => new BannerPicture() { PictureID = x }).ToList());
            }
            bannerServices.SaveBanner(banner);

            return RedirectToAction("Index");
        }
        public IActionResult EditBanner(int ID)
        {
            CreateBannerModel model = new CreateBannerModel();
            Banner banner = bannerServices.GetBannerByID(ID);
            model.ID = banner.ID;
            model.BannerName = banner.BannerName;
            model.BannerPictureList = banner.BannerPictures;
            return View(model);
        }
        [HttpPost]
        public IActionResult EditBanner(CreateBannerModel model)
        {
            Banner banner = new Banner();
            banner.ID = model.ID;
            banner.BannerName = model.BannerName;
            if (!string.IsNullOrEmpty(model.BannerPictures))
            {
                var pictureIDs = model.BannerPictures
                    .Split(new char[] { ',' },
                    StringSplitOptions.RemoveEmptyEntries)
                    .Select(ID => int.Parse(ID)).ToList();

                banner.BannerPictures = new List<BannerPicture>();
                banner.BannerPictures.AddRange(pictureIDs
                    .Select(x => new BannerPicture() { PictureID = x }).ToList());
            }
            bannerServices.UpdateBanner(banner);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(Banner banner)
        {
            bannerServices.DeleteBanner(banner);
            return RedirectToAction("Index");
        }
    }
}

Ecommerce.Web/Views/Banner/AddBanner.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content">
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action()"><i class="zmdi zmdi-home"></i> Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Banner</a></li>
                        <li class="breadcrumb-item active">Add New Banner Form</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <!-- Basic Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="body">
                            <form id="AddBannerForm" method="POST" action="@Url.Action("AddBanner","Banner")">
                                <div class="form-group form-float">
                                    <input type="text" class="form-control" placeholder="Banner Name" name="BannerName" required>
                                </div>

                                <div class="form-group">
                                    <label>Select Image</label>
                                    <input class="form-control" name="BannerPictures" id="bannerPictures" type="file" />
                                    <div id="picturesArea" class="form-group"></div>
                                    <input type="hidden" name="BannerPictures" id="PictureIDs" />
                                </div>
                                <button id="BannerAddBtn" class="btn btn-raised btn-primary waves-effect" type="button">SUBMIT</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div id="imageTemplate" style="display:none">
    <img class='image img-thumbnail' src='' style="height:100px; width:100px" />
</div>
<script>
    $('#BannerAddBtn').click(function () {
        debugger;
        var imageIDs = [];
        $("#picturesArea .image").each(function () {
            var imageID = $(this).attr("data-id");
            imageIDs.push(imageID);
        });
        $("#PictureIDs").val(imageIDs.join())
         $.ajax({
         url: "@Url.Action("AddBanner", "Banner")",
         type: "post",
             data: $("#AddBannerForm").serialize()
     }).done(function (responses) {
         debugger;
         alert("Banner Save Succesfully");
         window.location.href = "@Url.Action("Index","Banner")";

     }).fail(function () {

     });
    });

    $("#bannerPictures").change(function () {
          debugger;
          var pictures = this.files;
          var picsData = new FormData();
        for (var i = 0; i < pictures.length; i++) {
            picsData.append("Picture", pictures[i]);
        }
        $.ajax({
            url: "@Url.Action("UploadPictures","Shared")",
            type: "post",
            data: picsData,
            datatype: "json",
            processData: false,
            contentType: false
        }).done(function (responses) {
            debugger;
            for (var i = 0; i < responses.length; i++) {
                var picResponse = responses[i];

                AttachNewImage(picResponse.pictureUrl, picResponse.id);
            }
        }).fail(function () { });
    });

    function AttachNewImage(imageURL, imageID) {
        debugger;

        var $newImageHTML = $("#imageTemplate").clone();

        $newImageHTML.find(".image").attr("src", "@Url.Content("/Images/")" + imageURL);
        $newImageHTML.find(".image").attr("data-id", imageID);

        $("#picturesArea").append($newImageHTML.html());

        RemoveImageOnClick();

    }

    function RemoveImageOnClick() {
        $("#picturesArea .image").click(function () {

            debugger;
            $(this).remove();

        });
    }
</script>

Ecommerce.Web/Views/Banner/EditBanner.cshtml
@model Ecommerce.Web.Models.CreateBannerModel
@{
    ViewData["Title"] = "EditBanner";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var picture = Model.BannerPictureList;
}

<section class="content">
    <div class="body_scroll">
        <div class="block-header">
            <div class="row">
                <div class="col-lg-7 col-md-6 col-sm-12">
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="@Url.Action()"><i class="zmdi zmdi-home"></i> Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="javascript:void(0);">Banner</a></li>
                        <li class="breadcrumb-item active">Edit Banner Form</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <!-- Basic Validation -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="body">
                            <form id="EditBannerForm" method="POST" action="@Url.Action("EditBanner","Banner")">
                                <input type="hidden" value="@Model.ID" name="ID" />
                                <div class="form-group form-float">
                                    <input type="text" class="form-control" placeholder="Banner Name" name="BannerName" value="@Model.BannerName" required>
                                </div>

                                <div class="form-group">
                                    <label>
                                        Select Pictures
                                    </label>
                                    <input id="BannerPictures" type="file" name="BannerPictures" class="form-control" />
                                    <div id="picturesArea" class="form-group" style="margin-top:20px">
                                        @if (picture != null && picture.Count > 0)
                                        {
                                            foreach (var pictures in picture)
                                            {
                                                <img style="height:100px; width:100px" class='image img-thumbnail' src='~/Images/@pictures.Picture.PictureURL' data-id="@pictures.ID" />
                                            }
                                        }
                                        else { 
                                            <img style="height:100px; width:100px" class='image img-thumbnail' src='~/Images/default.jpg'/>
                                        }
                                    </div>
                                    <input type="hidden" name="BannerPictures" id="picturesIDs" />
                                </div>
                                <button id="BannerAddBtn" class="btn btn-raised btn-primary waves-effect" type="button">SUBMIT</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div id="imageTemplate" style="display:none">
    <img class='image img-thumbnail' src='' style="height:100px; width:100px" />
</div>
<script>
    $('#BannerAddBtn').click(function () {
        debugger;
        var imageIDs = [];
        $("#picturesArea .image").each(function () {
            var imageID = $(this).attr("data-id");
            imageIDs.push(imageID);
        });
        $("#PictureIDs").val(imageIDs.join())
         $.ajax({
         url: "@Url.Action("EditBanner", "Banner")",
         type: "post",
             data: $("#AddBannerForm").serialize()
     }).done(function (responses) {
         debugger;
         alert("Banner Save Succesfully");
         window.location.href = "@Url.Action("Index","Banner")";

     }).fail(function () {

     });
    });

    $("#BannerPictures").change(function () {
          debugger;
          var pictures = this.files;
          var picsData = new FormData();
        for (var i = 0; i < pictures.length; i++) {
            picsData.append("Picture", pictures[i]);
        }
        $.ajax({
            url: "@Url.Action("UploadPictures","Shared")",
            type: "post",
            data: picsData,
            datatype: "json",
            processData: false,
            contentType: false
        }).done(function (responses) {
            debugger;
            for (var i = 0; i < responses.length; i++) {
                var picResponse = responses[i];

                AttachNewImage(picResponse.pictureUrl, picResponse.id);
            }
        }).fail(function () { });
    });

    function AttachNewImage(imageURL, imageID) {
        debugger;

        var $newImageHTML = $("#imageTemplate").clone();

        $newImageHTML.find(".image").attr("src", "@Url.Content("/Images/")" + imageURL);
        $newImageHTML.find(".image").attr("data-id", imageID);

        $("#picturesArea").append($newImageHTML.html());

        RemoveImageOnClick();

    }

    function RemoveImageOnClick() {
        $("#picturesArea .image").click(function () {

            debugger;
            $(this).remove();

        });
    }
</script>

Ecommerce.Web/Views/Banner/Index.cshtml
@model IEnumerable<Ecommerce.Entities.Banner>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <a href="@Url.Action("AddBanner","Banner")" class="fa fa-edit btn btn-info">Add New Banner</a>
                    <h3 class="box-title" style="margin-left:300px">All Banner List Show</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                var picURL = item.BannerPictures != null && item.BannerPictures.Count > 0 ?
                                         "/Images/" +
                                             item.BannerPictures.First().Picture.PictureURL :
                                                    "/Images/default.jpg";
                                <tr>
                                    @if (picURL != null && picURL.Length > 0)
                                    {
                                        <td><img src="@picURL" width="48" alt="Product img"></td>
                                    }
                                    else { 
                                        <td><img src="~/Images/default.jpg" width="48" alt="Product img"></td>
                                    }
                                    
                                    <td>@item.BannerName</td>
                                    <td class="btn-group">
                                        <a href="@Url.Action("EditBanner","Banner",new { ID=item.ID})" class="btn btn-info">Edit</a>
                                        <button type="button" data-id="@item.ID" class="btn btn-danger bannerDeletebtn">Delete</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>


<script>
    $(".bannerDeletebtn").click(function () {
      debugger;
      var result = confirm("Are you sure delete this");
      if (result == true) {

          $.ajax({
              url: "@Url.Action("Delete","Banner")",
              method: "post",
              data: {

                  ID: $(this).attr("data-id")
              }
          }).done(function (response) {
              debugger;
              window.location.href = "@Url.Action("Index", "Banner")";
              $("#listingArea").html(response);
          });
      }
  });
</script>